#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
P1-1 articles batch — rank -> (class, declarations) mapping.
Single source of truth shared by fix_article_inline_styles.py and css generation.

Rank keys refer to d:/tmp/p11_articles_sorted_top150.txt (sorted-canonical 150).
`decls` are the CLEANED declarations (browser-computed equivalent of the inline
value, dropping invalid tokens / duplicate keys; last value wins).
Reused classes already defined in css/style.css — no def appended, only guard
(where needed) is emitted.
"""
RANKMAP = {
    1: ("cell-ddd", "border:1px solid #ddd;padding:8px"),
    2: ("cell-e2", "border:1px solid #e2e8f0;padding:10px"),
    3: ("img-block", "display:block;height:auto;margin:20px auto;max-width:100%"),
    4: ("text-accent", "color:#ff9800;font-weight:700"),
    5: ("table-scroll-mt", "margin:1rem 0;overflow-x:auto"),
    6: ("footer-micro", "border-top:1px solid #e0e0e0;color:#999;font-size:0.7rem;margin-top:0.5rem;padding-top:0.5rem"),
    7: ("img-block-frame", "border-radius:8px;border:1px solid #ddd;display:block;height:auto;margin:20px auto;max-width:100%"),
    8: ("cell-ccc", "border:1px solid #ccc;padding:8px"),
    9: ("tip-box", "background:#f8fafc;border-radius:8px;border:1px solid #e2e8f0;margin:2rem 0;padding:1.5rem"),
    10: ("tip-box-title", "color:#1e40af;font-weight:bold;margin:0 0 0.75rem 0"),
    11: ("list-flush", "margin:0;padding-left:1.2rem"),
    12: ("mt-0", "margin-top:0"),
    13: ("cell-dark", "border:1px solid #333;padding:10px"),
    14: ("text-gray-c", "color:#666;font-size:0.85rem;text-align:center"),
    15: ("btn-pill-orange", "background:#FF6600;border-radius:980px;color:#fff;display:inline-block;font-weight:600;padding:0.75rem 2rem;text-decoration:none"),
    16: ("card-mist-c", "background:#f8f9fa;border-radius:12px;border:1px solid #e0e0e0;margin:2rem 0;padding:1.5rem;text-align:center"),
    17: ("fs-lg-mb", "font-size:1.1rem;margin-bottom:0.75rem"),
    18: ("bg-mist", "background:#f8f9fa"),
    19: ("card-lg", "background:#f8f9fa;border-radius:8px;margin:3rem 0;padding:1.5rem"),
    20: ("grid-gap05", "display:grid;gap:0.5rem"),
    21: ("bg-navy", "background:#1a1a2e;color:#fff"),
    22: ("img-center", "display:block;height:auto;margin:0 auto"),
    23: ("cell-e2-12", "border:1px solid #e2e8f0;padding:8px 12px"),
    24: ("cell-e2-8", "border:1px solid #e2e8f0;padding:8px"),
    25: ("divider-mb", "border-bottom:1px solid #e2e8f0;margin-bottom:1.2rem;padding-bottom:1rem"),
    26: ("text-blue-lg", "color:#1e40af;font-size:1.05rem"),
    27: ("text-slate-mt03", "color:#475569;margin:0.3rem 0 0 0"),
    28: ("text-muted-c", "color:#888;font-size:0.9rem;text-align:center"),
    29: ("cell-ddd-6", "border:1px solid #ddd;padding:6px"),
    30: ("text-muted", "color:#888"),
    31: ("w-max860", "margin:0 auto;max-width:860px;padding:20px"),
    32: ("text-gray-xs", "color:#555;font-size:0.85rem"),
    33: ("note-left-blue-sm", "background:#f8f9fa;border-left:4px solid #2563eb;border-radius:8px;padding:1.2rem"),
    34: ("text-blue-mt0", "color:#2563eb;margin-top:0"),
    35: ("img-block-nodisplay", "height:auto;margin:20px auto;max-width:100%"),
    36: ("tbl-full", "border-collapse:collapse;margin:1rem 0;width:100%"),
    37: ("img-h", "height:auto"),
    38: ("figure-center", "margin:0 auto;text-align:center"),
    39: ("box-blue-lg", "background:#f0f7ff;border-radius:8px;margin:2rem 0;padding:20px"),
    40: ("text-blue-soft", "color:#93c5fd"),
    41: ("overflow-x", "overflow-x:auto"),
    42: ("note-left-navy", "background:#f0f7ff;border-left:4px solid #2a5298;border-radius:6px;font-size:0.95em;margin:1.2rem 0;padding:0.9rem 1rem"),
    43: ("text-navy-600", "color:#1e3c72;font-weight:600"),
    44: ("text-indigo-mt0", "color:#1e40af;margin-top:0"),
    45: ("footer-note", "border-top:1px solid #e0e0e0;color:#888888;font-size:12px;margin-top:40px;padding:20px 0;text-align:center"),
    46: ("margin-4", "margin:4px 0"),
    47: ("text-muted-sm-c", "color:#888;font-size:0.85rem;text-align:center"),
    48: ("mb-zero", "margin-bottom:0"),
    49: ("cell-gray-left", "background:#f5f5f5;border:1px solid #ddd;padding:8px;text-align:left"),
    50: ("text-emerald", "color:#10b981"),
    51: ("tbl-full-14", "border-collapse:collapse;font-size:14px;margin:1rem 0;width:100%"),
    52: ("text-green-lg", "color:#28a745;font-size:1rem;font-weight:bold"),
    53: ("text-green-600", "color:#16a34a;font-weight:600"),
    54: ("card-mt40", "background:#f8f9fa;border-radius:8px;clear:both;margin-top:40px;padding:24px"),
    55: ("text-muted-09em", "color:#666;font-size:0.9em"),
    56: ("figure-mt", "margin:2rem 0;text-align:center"),
    57: ("mt-30px", "margin-top:30px"),
    58: ("mt-11", "margin:1.1rem 0"),
    59: ("btn-orange", "background:#FF6600;border-radius:6px;color:#fff;display:inline-block;font-weight:600;padding:12px 24px;text-decoration:none"),
    60: ("cell-pad-left", "padding:8px 12px;text-align:left"),
    61: ("flex-row", "align-items:flex-start;border-bottom:1px solid #f0f0f0;display:flex;font-size:0.92rem;gap:0.75rem;padding:0.6rem 0"),
    62: ("text-green", "color:#28a745"),
    63: ("img-block-600", "display:block;height:auto;margin:20px auto;max-width:100%;width:600px"),
    64: ("cell-green", "border:1px solid #ddd;color:green;padding:8px"),
    65: ("img-shadow", "border-radius:8px;box-shadow:0 2px 12px rgba(0,0,0,0.06);display:block;height:auto;margin:20px auto;max-width:100%"),
    66: ("img-45", "border-radius:4px;border:1px solid #ddd;display:block;height:auto;margin:0 auto;max-width:400px;width:45%"),
    67: ("cell-p8", "padding:8px"),
    68: ("img-shadow-fl", "border-radius:8px;box-shadow:0 2px 12px rgba(0,0,0,0.06);height:auto;max-width:100%"),
    69: ("figcaption-sm-mt", "color:#888;font-size:0.85rem;margin-top:0.5rem"),
    70: ("text-small", "color:#666;font-size:0.9rem"),
    71: ("box-mb", "background:#f8fafc;border-radius:8px;margin-bottom:1rem;padding:1rem"),
    72: ("note-left-blue", "background:#f0f7ff;border-left:4px solid #2563eb;border-radius:8px;color:#1d1d1f;font-size:0.95rem;line-height:1.6;margin:1rem 0;padding:1rem 1.25rem"),
    73: ("cell-w35", "width:35%"),
    74: ("img-45-fl", "border-radius:4px;border:1px solid #ddd;height:auto;max-width:400px;width:45%"),
    75: ("margin-15-c", "margin:1.5rem 0;text-align:center"),
    76: ("w-max980-pad", "margin:0 auto;max-width:980px;padding:20px"),
    77: ("cell-p10", "padding:10px"),
    78: ("fs-lg", "font-size:1.1rem"),
    79: ("mt-05", "margin-top:0.5rem"),
    80: ("fw-600", "font-weight:600"),
    81: ("cta-band-dark", "background:#1a1a2e;color:#fff;margin-top:3rem;padding:2rem;text-align:center"),
    82: ("tbl-w100", "border-collapse:collapse;width:100%"),
    83: ("text-gray-mt", "color:#555;font-size:0.9rem;margin-top:1rem"),
    84: ("cell-w30", "width:30%"),
    85: ("text-gray-mb", "color:#555;font-size:0.9rem;margin-bottom:1rem"),
    86: ("fs-sm", "font-size:0.85rem"),
    87: ("tbl-w100-09", "border-collapse:collapse;font-size:0.9em;width:100%"),
    88: ("text-white-90", "color:rgba(255,255,255,0.9)"),
    89: ("box-gray", "background:#f9f9f9;border-radius:8px;border:1px solid #ddd;padding:20px"),
    90: ("text-navy-mt0", "color:#2c5aa0;margin-top:0"),
    91: ("btn-navy", "background:#2c5aa0;border-radius:4px;color:white;display:inline-block;margin-top:10px;padding:8px 16px;text-decoration:none"),
    92: ("grid-cards-300", "display:grid;gap:1.5rem;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));margin:1.5rem 0"),
    93: ("cta-gradient", "background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:#fff;margin:2rem 0;padding:3rem 1rem;text-align:center"),
    94: ("text-white-mb", "color:#fff;margin:0 0 0.75rem 0"),
    95: ("op-mb15", "margin:0 0 1.5rem 0;opacity:0.9"),
    96: ("cell-green-soft", "background:#e8f5e9;font-weight:700"),
    97: ("margin-20-c", "margin:20px 0;text-align:center"),
    98: ("cell-red", "background:#dc3545"),
    99: ("cell-green-bg", "background:#28a745"),
    100: ("text-red-strong", "color:#dc3545"),
    101: ("margin-0", "margin:0"),
    102: ("flex-wrap-20", "display:flex;flex-wrap:wrap;gap:10px;justify-content:center;margin:20px 0"),
    103: ("text-green-700", "color:#16a34a;font-weight:700"),
    104: ("bg-fa", "background:#f8fafc"),
    105: ("box-amber", "background:#fff7ed;border-radius:8px;border:1px solid #fed7aa;margin:2rem 0;padding:1.5rem"),
    106: ("cell-ddd-10", "border:1px solid #ddd;padding:10px"),
    107: ("mt-20", "margin-top:2rem"),
    108: ("mt-top-10", "margin-top:1rem"),
    109: ("card-mt40-fl", "background:#f8f9fa;border-radius:8px;margin-top:40px;padding:24px"),
    110: ("text-white", "color:#fff"),
    111: ("tbl-full-15", "border-collapse:collapse;margin:1.5rem 0;width:100%"),
    112: ("flex-wrap-15", "display:flex;flex-wrap:wrap;gap:1rem;margin:1.5rem 0"),
    113: ("img-400", "border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);display:block;height:auto;margin:0 auto;max-width:400px;width:100%"),
    114: ("bg-light", "background:#f5f5f7"),
    115: ("img-rounded", "border-radius:12px;margin:1.5rem 0;width:100%"),
    116: ("img-400-fl", "border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);height:auto;max-width:400px;width:100%"),
    117: ("tbl-full-20", "border-collapse:collapse;margin:20px 0;width:100%"),
    118: ("fs-sm-mt075", "font-size:0.9rem;margin-top:0.75rem"),
    119: ("text-center", "text-align:center"),
    120: ("img-w100", "border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);display:block;height:auto;margin:0 auto;width:100%"),
    121: ("figcaption-xs", "color:#666;font-size:0.85rem;margin-top:0.3rem"),
    122: ("text-azure", "color:#1a73e8"),
    123: ("w-max800", "margin:2rem auto;max-width:800px;padding:0 1.5rem"),
    124: ("text-gray-lg-lh", "color:#555;font-size:1.1rem;line-height:1.7"),
    125: ("btn-blue", "background:#2563eb;border-radius:8px;color:#fff;display:inline-block;font-weight:600;padding:12px 28px;text-decoration:none"),
    126: ("box-sm", "background:#f8f9fa;border-radius:8px;margin:1rem 0;padding:1rem"),
    127: ("text-navy2-mt0", "color:#1a1a2e;margin-top:0"),
    128: ("cta-dark-grad", "background:linear-gradient(135deg,#0c1a2e,#1a3a5c 50%,#0c4a6e);border-radius:14px;color:#fff;margin-bottom:2rem;padding:3rem 2rem;text-align:center"),
    129: ("list-none", "list-style:none;margin:1rem 0;padding:0"),
    130: ("flex-li", "align-items:flex-start;display:flex;font-size:0.92rem;gap:0.75rem;padding:0.6rem 0"),
    131: ("grid-cards-280", "display:grid;gap:1rem;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));margin:1.5rem 0"),
    132: ("text-gray-sm-c", "color:#555;font-size:0.9rem;text-align:center"),
    133: ("text-gray-mb-lg", "color:#555;font-size:0.9rem;margin-bottom:1.5rem"),
    134: ("text-dark-h4", "color:#333;font-size:0.95rem;margin-bottom:1rem"),
    135: ("text-gray-xs-lh", "color:#555;font-size:0.88rem;line-height:1.7;margin-bottom:1rem"),
    136: ("margin-2rem", "margin:2rem 0"),
    137: ("box-xs", "background:#f8f9fa;border-radius:6px;font-size:0.9rem;padding:0.75rem"),
    138: ("box-blue-border", "background:#f0f7ff;border-radius:8px;border:1px solid #cce5ff;margin-top:2rem;padding:1.5rem"),
    139: ("img-w100-fl", "margin:0 auto;width:100%"),
    140: ("text-amber", "color:#f59e0b"),
    141: ("text-muted-09em-8", "color:#888;font-size:0.9em"),
    142: ("cell-e2-bold", "border:1px solid #e2e8f0;font-weight:600;padding:8px"),
    143: ("mt-075", "margin-top:0.75rem"),
    144: ("btn-blue-sm", "background:#2563eb;border-radius:6px;color:#fff;display:inline-block;font-weight:600;padding:10px 24px;text-decoration:none"),
    145: ("bg-green-pale", "background:#f0fdf4"),
    146: ("m-15y", "margin:1.5rem 0"),
    147: ("btn-outline-grad", "background:#fff;border-radius:8px;color:#667eea;display:inline-block;font-size:1.1rem;font-weight:700;padding:14px 36px;text-decoration:none"),
    148: ("fs-sm-mt-op", "font-size:0.85rem;margin-top:1rem;opacity:0.8"),
    149: ("box-mb-lg", "background:#f8fafc;border-radius:8px;margin-bottom:1.5rem;padding:1rem"),
    150: ("btn-outline-grad-sm", "background:#fff;border-radius:8px;color:#667eea;display:inline-block;font-weight:700;padding:14px 36px;text-decoration:none"),
}

# classes already defined standalone in css/style.css (exact props match) — no def appended.
REUSED = {
    "footer-micro", "tip-box", "tip-box-title", "list-flush", "mt-0",
    "text-blue-soft", "overflow-x", "text-muted-sm-c", "mt-11", "btn-orange",
    "text-small", "cta-band-dark", "fs-sm", "bg-light", "mt-top-10",
    "text-center", "footer-note", "text-white", "btn-navy", "cell-e2", "cell-e2-8",
    "cell-e2-12", "tbl-full", "tbl-w100", "tbl-full-14", "flex-row", "flex-li",
}

# .text-accent exists only as a.text-accent (compound) — emit standalone def.
# .text-muted exists only as .text-muted:hover — emit standalone def.
STANDALONE = {
    "text-accent": "color:#ff9800;font-weight:700",
    "text-muted": "color:#888",
}

# cls -> guard selector (defs identical to the class; compound beats base rules).
GUARDS = {
    "mt-0": ".post h2.mt-0,.post h3.mt-0,.post h4.mt-0",
    "text-blue-lg": ".post h2.text-blue-lg,.post h3.text-blue-lg,.post h4.text-blue-lg",
    "text-blue-mt0": ".post h2.text-blue-mt0,.post h3.text-blue-mt0,.post h4.text-blue-mt0",
    "text-indigo-mt0": ".post h2.text-indigo-mt0,.post h3.text-indigo-mt0,.post h4.text-indigo-mt0",
    "text-navy-mt0": ".post h2.text-navy-mt0,.post h3.text-navy-mt0,.post h4.text-navy-mt0",
    "text-white-mb": ".post h2.text-white-mb,.post h3.text-white-mb,.post h4.text-white-mb",
    "text-white": ".post .content a.text-white,.post h2.text-white,.post h3.text-white,.post h4.text-white",
    "text-navy2-mt0": ".post h2.text-navy2-mt0,.post h3.text-navy2-mt0,.post h4.text-navy2-mt0",
    "text-dark-h4": ".post h2.text-dark-h4,.post h3.text-dark-h4,.post h4.text-dark-h4",
    "tip-box-title": ".post .content p.tip-box-title",
    "fs-lg-mb": ".post .content p.fs-lg-mb",
    "text-slate-mt03": ".post .content p.text-slate-mt03",
    "text-muted-c": ".post figcaption.text-muted-c,.post .content figcaption.text-muted-c,.post .content p.text-muted-c",
    "text-muted-sm-c": ".post figcaption.text-muted-sm-c,.post .content figcaption.text-muted-sm-c,.post .content p.text-muted-sm-c",
    "figcaption-sm-mt": ".post figcaption.figcaption-sm-mt,.post .content figcaption.figcaption-sm-mt,.post .content p.figcaption-sm-mt",
    "figcaption-xs": ".post figcaption.figcaption-xs,.post .content figcaption.figcaption-xs,.post .content p.figcaption-xs",
    "tbl-full": ".post table.tbl-full,.post .content table.tbl-full,.post .table-wrap table.tbl-full",
    "tbl-full-14": ".post table.tbl-full-14,.post .content table.tbl-full-14,.post .table-wrap table.tbl-full-14",
    "tbl-w100": ".post table.tbl-w100,.post .content table.tbl-w100,.post .table-wrap table.tbl-w100",
    "tbl-w100-09": ".post table.tbl-w100-09,.post .content table.tbl-w100-09,.post .table-wrap table.tbl-w100-09",
    "tbl-full-15": ".post table.tbl-full-15,.post .content table.tbl-full-15,.post .table-wrap table.tbl-full-15",
    "tbl-full-20": ".post table.tbl-full-20,.post .content table.tbl-full-20,.post .table-wrap table.tbl-full-20",
    "text-muted": ".post .content a.text-muted",
    "btn-pill-orange": ".post .content a.btn-pill-orange",
    "btn-navy": ".post .content a.btn-navy",
    "figure-center": ".post figure.figure-center,.post .content figure.figure-center",
    "figure-mt": ".post figure.figure-mt,.post .content figure.figure-mt",
    "margin-0": ".post figure.margin-0,.post .content figure.margin-0,.post .content p.margin-0",
    "margin-4": ".post .content p.margin-4",
    "img-block": ".post img.img-block,.post .content img.img-block",
    "img-block-frame": ".post img.img-block-frame,.post .content img.img-block-frame,.post .content figure img.img-block-frame",
    "img-center": ".post img.img-center,.post .content img.img-center",
    "img-block-nodisplay": ".post img.img-block-nodisplay,.post .content img.img-block-nodisplay",
    "img-block-600": ".post img.img-block-600,.post .content img.img-block-600",
    "img-shadow": ".post img.img-shadow,.post .content img.img-shadow,.post .content figure img.img-shadow",
    "img-45": ".post img.img-45,.post .content img.img-45,.post .content figure img.img-45",
    "img-45-fl": ".post .content figure img.img-45-fl",
    "img-400": ".post img.img-400,.post .content img.img-400,.post .content figure img.img-400",
    "img-rounded": ".post img.img-rounded,.post .content img.img-rounded,.post .content figure img.img-rounded",
    "img-w100": ".post img.img-w100,.post .content img.img-w100,.post .content figure img.img-w100",
    "img-w100-fl": ".post img.img-w100-fl,.post .content img.img-w100-fl",
}
